imports:
    - resource: config.yaml

services:
    plg_stripe_rec.service.admin.plugin.config:
        public: true
        class: Plugin\StripeRec\Service\Admin\ConfigService
        arguments:
            - '@service_container'
    plg_stripe_rec.service.email.service:
        public: true
        class: Plugin\StripeRec\Service\MailExService
        arguments:
            - '@service_container'
    plg_stripe_rec.service.util:
        public: true
        class: Plugin\StripeRec\Service\UtilService
        arguments:
            - '@service_container'
    plg_stripe_rec.service.product_service:
        public: true
        class: Plugin\StripeRec\Service\Admin\ProductRecService
        arguments:
            - '@service_container'
    plg_stripe_rec.service.stripe_service:
        public: true
        class: Plugin\StripeRec\Service\StripeService
        arguments:
            - '@service_container'